-- Expand the locations list with most Sydney metro suburbs.
-- Uses INSERT OR IGNORE so re-running is safe and existing rows (cbd, surry-hills, etc.) are kept.

INSERT OR IGNORE INTO locations (slug, name) VALUES
  -- CBD & surrounds
  ('cbd', 'Sydney CBD'),
  ('the-rocks', 'The Rocks'),
  ('millers-point', 'Millers Point'),
  ('walsh-bay', 'Walsh Bay'),
  ('dawes-point', 'Dawes Point'),
  ('barangaroo', 'Barangaroo'),
  ('haymarket', 'Haymarket'),
  ('chinatown', 'Chinatown'),
  ('pyrmont', 'Pyrmont'),
  ('ultimo', 'Ultimo'),
  ('darling-harbour', 'Darling Harbour'),

  -- Inner east
  ('woolloomooloo', 'Woolloomooloo'),
  ('potts-point', 'Potts Point'),
  ('elizabeth-bay', 'Elizabeth Bay'),
  ('rushcutters-bay', 'Rushcutters Bay'),
  ('kings-cross', 'Kings Cross'),
  ('darlinghurst', 'Darlinghurst'),
  ('surry-hills', 'Surry Hills'),
  ('paddington', 'Paddington'),
  ('edgecliff', 'Edgecliff'),
  ('darling-point', 'Darling Point'),
  ('double-bay', 'Double Bay'),
  ('bellevue-hill', 'Bellevue Hill'),
  ('rose-bay', 'Rose Bay'),
  ('point-piper', 'Point Piper'),
  ('vaucluse', 'Vaucluse'),
  ('watsons-bay', 'Watsons Bay'),
  ('dover-heights', 'Dover Heights'),
  ('woollahra', 'Woollahra'),
  ('centennial-park', 'Centennial Park'),
  ('moore-park', 'Moore Park'),

  -- Eastern beaches
  ('bondi', 'Bondi'),
  ('bondi-beach', 'Bondi Beach'),
  ('bondi-junction', 'Bondi Junction'),
  ('north-bondi', 'North Bondi'),
  ('tamarama', 'Tamarama'),
  ('bronte', 'Bronte'),
  ('waverley', 'Waverley'),
  ('queens-park', 'Queens Park'),
  ('clovelly', 'Clovelly'),
  ('coogee', 'Coogee'),
  ('randwick', 'Randwick'),
  ('kensington', 'Kensington'),
  ('kingsford', 'Kingsford'),
  ('maroubra', 'Maroubra'),
  ('matraville', 'Matraville'),
  ('malabar', 'Malabar'),
  ('little-bay', 'Little Bay'),
  ('chifley', 'Chifley'),
  ('pagewood', 'Pagewood'),
  ('hillsdale', 'Hillsdale'),
  ('eastgardens', 'Eastgardens'),
  ('banksmeadow', 'Banksmeadow'),
  ('botany', 'Botany'),
  ('mascot', 'Mascot'),
  ('daceyville', 'Daceyville'),

  -- Inner south
  ('rosebery', 'Rosebery'),
  ('eastlakes', 'Eastlakes'),
  ('alexandria', 'Alexandria'),
  ('waterloo', 'Waterloo'),
  ('zetland', 'Zetland'),
  ('beaconsfield', 'Beaconsfield'),
  ('redfern', 'Redfern'),
  ('erskineville', 'Erskineville'),
  ('st-peters', 'St Peters'),
  ('sydenham', 'Sydenham'),
  ('tempe', 'Tempe'),
  ('marrickville', 'Marrickville'),
  ('enmore', 'Enmore'),
  ('newtown', 'Newtown'),
  ('camperdown', 'Camperdown'),
  ('darlington', 'Darlington'),
  ('chippendale', 'Chippendale'),
  ('glebe', 'Glebe'),
  ('forest-lodge', 'Forest Lodge'),
  ('annandale', 'Annandale'),
  ('stanmore', 'Stanmore'),
  ('petersham', 'Petersham'),
  ('dulwich-hill', 'Dulwich Hill'),
  ('hurlstone-park', 'Hurlstone Park'),
  ('lewisham', 'Lewisham'),
  ('summer-hill', 'Summer Hill'),
  ('ashfield', 'Ashfield'),
  ('haberfield', 'Haberfield'),
  ('leichhardt', 'Leichhardt'),
  ('lilyfield', 'Lilyfield'),
  ('rozelle', 'Rozelle'),
  ('balmain', 'Balmain'),
  ('balmain-east', 'Balmain East'),
  ('birchgrove', 'Birchgrove'),
  ('croydon', 'Croydon'),
  ('burwood', 'Burwood'),
  ('concord', 'Concord'),
  ('strathfield', 'Strathfield'),
  ('homebush', 'Homebush'),
  ('homebush-west', 'Homebush West'),
  ('north-strathfield', 'North Strathfield'),
  ('rhodes', 'Rhodes'),

  -- North (Lower North Shore)
  ('milsons-point', 'Milsons Point'),
  ('kirribilli', 'Kirribilli'),
  ('north-sydney', 'North Sydney'),
  ('mcmahons-point', 'McMahons Point'),
  ('waverton', 'Waverton'),
  ('lavender-bay', 'Lavender Bay'),
  ('wollstonecraft', 'Wollstonecraft'),
  ('crows-nest', 'Crows Nest'),
  ('st-leonards', 'St Leonards'),
  ('neutral-bay', 'Neutral Bay'),
  ('cremorne', 'Cremorne'),
  ('cremorne-point', 'Cremorne Point'),
  ('mosman', 'Mosman'),
  ('balmoral', 'Balmoral'),
  ('clifton-gardens', 'Clifton Gardens'),
  ('beauty-point', 'Beauty Point'),
  ('cammeray', 'Cammeray'),
  ('northbridge', 'Northbridge'),
  ('castlecrag', 'Castlecrag'),
  ('middle-cove', 'Middle Cove'),
  ('willoughby', 'Willoughby'),
  ('artarmon', 'Artarmon'),
  ('lane-cove', 'Lane Cove'),
  ('greenwich', 'Greenwich'),
  ('chatswood', 'Chatswood'),
  ('roseville', 'Roseville'),
  ('lindfield', 'Lindfield'),
  ('killara', 'Killara'),
  ('gordon', 'Gordon'),
  ('pymble', 'Pymble'),
  ('st-ives', 'St Ives'),
  ('turramurra', 'Turramurra'),
  ('warrawee', 'Warrawee'),
  ('wahroonga', 'Wahroonga'),
  ('hornsby', 'Hornsby'),
  ('waitara', 'Waitara'),
  ('normanhurst', 'Normanhurst'),
  ('thornleigh', 'Thornleigh'),
  ('pennant-hills', 'Pennant Hills'),
  ('west-pennant-hills', 'West Pennant Hills'),

  -- Northern beaches
  ('manly', 'Manly'),
  ('fairlight', 'Fairlight'),
  ('balgowlah', 'Balgowlah'),
  ('seaforth', 'Seaforth'),
  ('clontarf', 'Clontarf'),
  ('freshwater', 'Freshwater'),
  ('curl-curl', 'Curl Curl'),
  ('dee-why', 'Dee Why'),
  ('brookvale', 'Brookvale'),
  ('collaroy', 'Collaroy'),
  ('narrabeen', 'Narrabeen'),
  ('warriewood', 'Warriewood'),
  ('mona-vale', 'Mona Vale'),
  ('newport', 'Newport'),
  ('avalon', 'Avalon Beach'),
  ('whale-beach', 'Whale Beach'),
  ('palm-beach', 'Palm Beach'),

  -- Inner west (further)
  ('five-dock', 'Five Dock'),
  ('drummoyne', 'Drummoyne'),
  ('russell-lea', 'Russell Lea'),
  ('abbotsford', 'Abbotsford'),
  ('wareemba', 'Wareemba'),
  ('canada-bay', 'Canada Bay'),

  -- West
  ('parramatta', 'Parramatta'),
  ('harris-park', 'Harris Park'),
  ('rosehill', 'Rosehill'),
  ('granville', 'Granville'),
  ('auburn', 'Auburn'),
  ('lidcombe', 'Lidcombe'),
  ('flemington', 'Flemington'),
  ('olympic-park', 'Sydney Olympic Park'),
  ('west-ryde', 'West Ryde'),
  ('ryde', 'Ryde'),
  ('meadowbank', 'Meadowbank'),
  ('eastwood', 'Eastwood'),
  ('epping', 'Epping'),
  ('carlingford', 'Carlingford'),
  ('north-ryde', 'North Ryde'),
  ('macquarie-park', 'Macquarie Park'),
  ('north-parramatta', 'North Parramatta'),
  ('westmead', 'Westmead'),
  ('wentworthville', 'Wentworthville'),

  -- South
  ('st-george', 'St George'),
  ('kogarah', 'Kogarah'),
  ('hurstville', 'Hurstville'),
  ('allawah', 'Allawah'),
  ('carlton', 'Carlton'),
  ('rockdale', 'Rockdale'),
  ('brighton-le-sands', 'Brighton-Le-Sands'),
  ('kyeemagh', 'Kyeemagh'),
  ('arncliffe', 'Arncliffe'),
  ('wolli-creek', 'Wolli Creek'),
  ('bexley', 'Bexley'),
  ('ramsgate', 'Ramsgate'),
  ('monterey', 'Monterey'),
  ('sans-souci', 'Sans Souci'),
  ('blakehurst', 'Blakehurst'),
  ('oatley', 'Oatley'),
  ('penshurst', 'Penshurst'),
  ('mortdale', 'Mortdale'),
  ('cronulla', 'Cronulla'),
  ('miranda', 'Miranda'),
  ('caringbah', 'Caringbah'),
  ('sylvania', 'Sylvania'),
  ('gymea', 'Gymea'),
  ('sutherland', 'Sutherland'),

  -- Southwest
  ('canterbury', 'Canterbury'),
  ('campsie', 'Campsie'),
  ('earlwood', 'Earlwood'),
  ('belmore', 'Belmore'),
  ('lakemba', 'Lakemba'),
  ('wiley-park', 'Wiley Park'),
  ('punchbowl', 'Punchbowl'),
  ('bankstown', 'Bankstown'),
  ('greenacre', 'Greenacre'),
  ('padstow', 'Padstow'),
  ('revesby', 'Revesby'),
  ('panania', 'Panania'),
  ('cabramatta', 'Cabramatta'),
  ('canley-vale', 'Canley Vale'),
  ('canley-heights', 'Canley Heights'),
  ('fairfield', 'Fairfield'),
  ('liverpool', 'Liverpool');

-- A handful of common cuisine entries in a new tiny table — purely for the cuisine datalist.
-- (Cuisines live as free-text on restaurants; this is just an autocomplete seed.)
CREATE TABLE IF NOT EXISTS cuisine_suggestions (
  name TEXT PRIMARY KEY
);

INSERT OR IGNORE INTO cuisine_suggestions (name) VALUES
  ('Modern Australian'),
  ('Japanese'), ('Sushi'), ('Ramen'), ('Izakaya'), ('Yakitori'),
  ('Chinese'), ('Cantonese'), ('Sichuan'), ('Hot Pot'), ('Dim Sum'), ('Dumplings'),
  ('Korean'), ('Korean BBQ'),
  ('Thai'),
  ('Vietnamese'), ('Pho'), ('Bánh Mì'),
  ('Malaysian'), ('Singaporean'), ('Indonesian'), ('Filipino'),
  ('Indian'), ('North Indian'), ('South Indian'), ('Sri Lankan'),
  ('Italian'), ('Pizza'), ('Pasta'),
  ('French'), ('Bistro'), ('Bakery'), ('Pâtisserie'),
  ('Spanish'), ('Tapas'),
  ('Greek'),
  ('Turkish'), ('Middle Eastern'), ('Lebanese'),
  ('Mexican'), ('Latin American'),
  ('American'), ('Burgers'), ('BBQ'), ('Diner'),
  ('Seafood'), ('Steakhouse'), ('Pub'), ('Gastropub'),
  ('Cafe'), ('Brunch'), ('Breakfast'),
  ('Dessert'), ('Ice Cream'), ('Gelato'),
  ('Vegan'), ('Vegetarian'),
  ('Fusion'), ('Contemporary'),
  ('Wine Bar'), ('Cocktail Bar'),
  ('African'), ('Ethiopian');
