-- Generated by scripts/classify-vego.mjs on 2026-08-10T10:38:19.780Z
-- 25 of 298 places classified "great for vegetarians".

UPDATE tags SET label = 'Great for vegetarians' WHERE slug = 'vegetarian';

DELETE FROM restaurant_tags
 WHERE tag_id = (SELECT id FROM tags WHERE slug = 'vegetarian');

INSERT INTO restaurant_tags (restaurant_id, tag_id)
SELECT res.id, (SELECT id FROM tags WHERE slug = 'vegetarian')
  FROM restaurants res
 WHERE res.slug IN ('anason', 'chao-praya', 'co-ba-marrickville', 'cubby-s-kitchen', 'don-t-tell-uncle', 'emma-s-snack-bar-2', 'ezra', 'foreign-return-indian-restaurant', 'jambo-jambo', 'jasmine1', 'jimmy-s-falafel', 'kepos-street-kitchen', 'legend-hotpot-buffet', 'mango-coco', 'maydanoz-restaurant-bar', 'nomad', 'nour', 'shaffa', 'shuk', 'spice-temple-sydney', 'tao-restaurant', 'teras', 'time-for-thai', 'turka-cafe', 'two-chaps');
